import { Inter } from "next/font/google";
import "./globals.css";
import ClickSpark from "@/components/ClickSpark";
import SparklesIcon from "@/components/sparklesIcon";
import Link from "next/link";
import page from "./Pricing/page"

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Caption gentretor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          " bg-gradient-to-b from-purple-800 to-blue-[#7C4AFF] min-h-screen"
        }
      ><ClickSpark
          sparkColor="#b363e9ff"
          sparkSize={10}
          sparkRadius={15}
          sparkCount={8}
          duration={400}
        >
        <main className="p-4  max-w-4xl max-auto">
        
          <header className="flex justify-between my-8 text-white">
                  <Link href="/" className="flex gap-1 items-center">
                <SparklesIcon aria-hidden="true" />
                <span>EpicCaption</span>
              </Link>
                  <nav className="flex gap-6 text-white/80">
                    <Link href="/" >Home</Link>
                    <Link href="/Pricing">Pricing</Link>

                   <a href="mailto:contact@epiccaptions.com">Contect</a>
                  </nav>
                </header>
          {children}
        
        </main>
        </ClickSpark>
      </body>
    </html>
  );
}
